export const CONTRACT_ADDRESS_PVP =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_PVP;
export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS;
export const CONTRACT_ADDRESS_NEKO_LOTTERY =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_NEKO_LOTTERY;
export const CONTRACT_ADDRESS_BATTLE_ROYALE =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_BATTLE_ROYALE;
export const CONTRACT_ADDRESS_MEME_COIN_FLIP =
  process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_MEME_COIN_FLIP;
export const GAS = process.env.NEXT_PUBLIC_GAS;
export const ZEALY_KEY = process.env.NEXT_PUBLIC_ZEALY_KEY;
export const ZEALY_API = process.env.NEXT_PUBLIC_ZEALEY_API;
